name: Keep Render App Alive

on:
  schedule:
    # Runs every 14 minutes to prevent 15-minute auto-sleep
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the app
        run: |
          curl -f https://influencerinsight-2.onrender.com/api/health || echo "App might be sleeping, but ping sent"
